In [22]:
import mne
import numpy as np
from pandas import DataFrame
import pandas as pd
import matplotlib.pyplot as plt
import pickle

In [2]:
path1 = "chb-mit-scalp-eeg-database-1.0.0/chb01/chb01_15.edf"
chb01_15_raw = mne.io.read_raw_edf(path1)

Extracting EDF parameters from /home/npe/Documents/Seizure Prediction/chb-mit-scalp-eeg-database-1.0.0/chb01/chb01_15.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...


<ipython-input-2-bb0a83c2ba9a>:2: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  chb01_15_raw = mne.io.read_raw_edf(path1)


In [3]:
# chb01_15_raw.load_data()

In [4]:
# chb01_15_raw.apply_hilbert()

In [5]:
chb01_15_raw.info

<Info | 7 non-empty values
 bads: []
 ch_names: FP1-F7, F7-T7, T7-P7, P7-O1, FP1-F3, F3-C3, C3-P3, P3-O1, ...
 chs: 23 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 128.0 Hz
 meas_date: 1976-11-07 01:44:44 UTC
 nchan: 23
 projs: []
 sfreq: 256.0 Hz
>

In [19]:
a = mne.time_frequency.psd_welch(inst=chb01_15_raw, picks='F7-T7')

Effective window size : 1.000 (s)


In [21]:
a

(array([[1.02532247e-10, 6.76087553e-10, 5.09043730e-10, ...,
         8.46227391e-15, 1.46609487e-14, 8.18009253e-15],
        [7.31415870e-11, 4.94071874e-10, 3.72738073e-10, ...,
         1.54210637e-14, 2.17411430e-14, 1.04053002e-14],
        [1.18489438e-10, 7.77746528e-10, 4.68531127e-10, ...,
         8.90337661e-15, 1.00291977e-14, 5.58347798e-15],
        ...,
        [1.58921677e-10, 9.42040783e-10, 6.55611792e-10, ...,
         1.97203356e-14, 2.05484861e-14, 2.11090846e-14],
        [5.40407875e-11, 3.44841400e-10, 2.43837067e-10, ...,
         3.45028363e-14, 3.60754536e-14, 2.13608507e-14],
        [1.64614191e-10, 1.14665711e-09, 7.06289892e-10, ...,
         3.43866442e-14, 3.41850258e-14, 2.10202352e-14]]),
 array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,

In [23]:
with open('data.txt', 'wb') as file:
    pickle.dump(a, file)

In [25]:
with open('data.txt', 'rb') as file:
    b = pickle.load(file)

In [26]:
b

(array([[1.02532247e-10, 6.76087553e-10, 5.09043730e-10, ...,
         8.46227391e-15, 1.46609487e-14, 8.18009253e-15],
        [7.31415870e-11, 4.94071874e-10, 3.72738073e-10, ...,
         1.54210637e-14, 2.17411430e-14, 1.04053002e-14],
        [1.18489438e-10, 7.77746528e-10, 4.68531127e-10, ...,
         8.90337661e-15, 1.00291977e-14, 5.58347798e-15],
        ...,
        [1.58921677e-10, 9.42040783e-10, 6.55611792e-10, ...,
         1.97203356e-14, 2.05484861e-14, 2.11090846e-14],
        [5.40407875e-11, 3.44841400e-10, 2.43837067e-10, ...,
         3.45028363e-14, 3.60754536e-14, 2.13608507e-14],
        [1.64614191e-10, 1.14665711e-09, 7.06289892e-10, ...,
         3.43866442e-14, 3.41850258e-14, 2.10202352e-14]]),
 array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
         11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
         22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
         33.,  34.,  35.,  36.,  37.,  38.,